id: P010759
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:23:13.731078
source_metadata:
  id: bdr:W2124
  title: གྲུབ་མཐའ་ཤེལ་གྱི་མེ་ལོང
  author: ''
  volumes:
    0fc5348f5ced4697b3711870d1eee334:
      image_group_id: I1GS105573
      title: ''
      volume_number: 1
      total_pages: 506
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
